### ISSUE TITLE
User testing - helpful workflow metadata fields

### ISSUE THREAD

**Issue by atrisovic** [gdcc/swc.wgs.gdcc.io#7]
Users are to be asked to check out helpful metadata fields - both for documenting their own workflow and understanding others' workflows.

## Part I

- [ ] `creator` - The creator/author of this CreativeWork.
- [ ] `dateCreated` - The date on which the CreativeWork was created.
- [ ] `input` - An input required to use the computational workflow (eg. Excel spreadsheet, BAM file)
- [ ] `license` - A license document that applies to this content, typically indicated by URL.
- [ ] `name` - The name of the item.
- [ ] `output` - An output produced by the workflow.
- [ ] `programmingLanguage` - The computer programming language.
- [ ] `sdPublisher` - Indicates the party responsible for generating and publishing the current structured data markup, typically in cases where the structured data is derived automatically from existing published content but published on a different site.
- [ ] `url` - URL of the item.
- [ ] `version` - The version of the CreativeWork embodied by a specified resource.

## Part II
	
- [ ] `citation` - A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.
- [ ] `contributor` - A secondary contributor to the CreativeWork or Event.
- [ ] `creativeWorkStatus` - The status of a creative work in terms of its stage in a lifecycle. Example terms include Incomplete, Draft, Published, Obsolete. 
- [ ] `description` - A description of the item.
- [ ] `documentation` - Documentation describing the ComputationalWorkflow and its use.
- [ ] `funding` - The funding for the workflow.
- [ ] `hasPart` - Indicates an item or CreativeWork that is part of this item, or CreativeWork (in some sense). 
- [ ] `isBasedOn` - A resource from which this work is derived or from which it is a modification or adaption (eg. another ComputationalWorkflow, a paper or a lab protocol). 
- [ ] `keywords` - Keywords or tags used to describe this content. Multiple entries in a keywords list are typically delimited by commas.
- [ ] `maintainer` - A maintainer of a Dataset, software package (SoftwareApplication), or other Project. 
- [ ] `producer` - The person or organization who produced the workflow.
- [ ] `publisher` - The publisher of the creative work (e.g. Galaxy, github, or WF Hub).
- [ ] `runtimePlatform	Text	R	Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0). Supersedes runtime.
- [ ] `softwareRequirements	"Text
- [ ] `URL"	R	Component dependency requirements for application. This includes runtime environments and shared libraries that are not included in the application distribution package, but required to run the application (Examples: DirectX, Java or .NET runtime). Supersedes requirements.
- [ ] `targetProduct	SoftwareApplication	R	Target Operating System / Product to which the code applies. If applies to several versions, just the product name can be used.

## Part III 
		
- [ ] `alternateName` -	An alias for the item.
- [ ] `conditionsOfAccess	Text	NR	Conditions that affect the availability of, or method(s) of access to, an item. Typically used for real world items such as an ArchiveComponent held by an ArchiveOrganization. This property is not suitable for use as a general Web access control mechanism. It is expressed only in natural language.
- [ ] `dateModified` - The date on which the CreativeWork was most recently modified.
- [ ] `datePublished` - Date of first broadcast/publication.
- [ ] `encodingFormat` - Media type typically expressed using a MIME format (see IANA siteand MDN reference) e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.). 
- [ ] `image` - An image of the item.

## Part IV

- [ ] `codeRepository`
- [ ] `applicationCategory`
- [ ] `applicationSubCategory`
- [ ] `fileSize`
- [ ] `memoryRequirements`
- [ ] `operatingSystem`
- [ ] `processorRequirements`
- [ ] `softwareHelp`
- [ ] `storageRequirements`
- [ ] `supportingData`
- [ ] `copyrightHolder`
- [ ] `copyrightYear`
- [ ] `editor`
- [ ] `encoding`
- [ ] `provider`
- [ ] `sponsor`
- [ ] `isAccessibleForFree`
- [ ] `isPartOf`
- [ ] `position`
- [ ] `sameAs`
- [ ] `relatedLink`
- [ ] `softwareSuggestions`
- [ ] `contIntegration`
- [ ] `developmentStatus`
- [ ] `embargoDate`
- [ ] `issueTracker`
- [ ] `referencePublication`
